name:               "YangXin--兄弟会-"
description:        "The harder you work, the luckier you will be"

url:                "https://yangxin19970404.github.io"
email:              "yangxin19970404@163.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
email:              "yangxin19970404@163.com"
github:             "https://github.com/yangxin19970404"


disqus_shortname:   "thinker3197"

background:         "https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=3016321503,1563649456&fm=26&gp=0.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Aboutme"
    href:           "https://github.com/yangxin19970404"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
