name:               "YangXin--兄弟会-"
description:        "先谋生，再谋爱！"

url:                "https://yangxin19970404.github.io"
email:              "yangxin19970404@163.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
facebook:           "jhondoe"
linkedin:           "jhondoe"




disqus_shortname:   "yangxin19970404"

background:         "https://p3a.pstatp.com/weili/l/189489516171755872.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "MyGithub"
    href:           "https://github.com/yangxin19970404"


sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"


